---
# vim: set ft=yaml:

# # TODO: Also need to install CRDs
# kubectl kustomize "https://github.com/redpanda-data/redpanda-operator//src/go/k8s/config/crd?ref=v2.1.14-23.3.4" \
# | kubectl apply -f -
# - name: Deploy Operator
#   delegate_to: localhost
#   kubernetes.core.helm:
#     name: redpanda-operator
#     create_namespace: true
#     chart_ref: "{{ q('pipe', 'git rev-parse --show-toplevel')[0] }}/charts/redpanda-operator-helm/charts/operator"
#     # chart_version: 0.8.2
#     wait: true
#     release_namespace: redpanda
#     values: "{{ lookup('ansible.builtin.template', 'operator-values.yaml.j2') | from_yaml }}"

# - name: Debug YAML output
#   debug:
#     msg: "{{ lookup('ansible.builtin.template', item) | from_yaml }}"
#   with_fileglob:
#     - "../templates/helm*.j2"

- name: Deploy Cert-Manager
  delegate_to: localhost
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    create_namespace: yes
    # chart_version: 0.8.2
    wait: true
    release_namespace: cert-manager
    values: "{{ lookup('ansible.builtin.template', 'cert-manager-values.yaml.j2') | from_yaml }}"


- name: Deploy Redpanda
  delegate_to: localhost
  kubernetes.core.helm:
    name: redpanda
    create_namespace: true
    chart_ref: "{{ q('pipe', 'git rev-parse --show-toplevel')[0] }}/charts/redpanda-operator-helm/charts/redpanda"
    # chart_version: 0.8.2
    wait: true
    release_namespace: redpanda
    values: "{{ lookup('ansible.builtin.template', 'helm-values.yaml.j2') | from_yaml }}"

# - name: Enable write caching
#   when: exp_params.redpanda_write_caching
#   ansible.builtin.k8s:
#     definition:
#       apiVersion: batch/v1
#       kind: Job
#       metadata:
#         name: enable-write-caching
#         namespace: redpanda
#       spec:
#         template:
#           spec:
#             containers:
#               - name: rpk
#                 image: vectorized/redpanda:v24.1.8
#                 command: ["/bin/sh", "-c"]
#                 args:
#                   - rpk cluster config -X admin.hosts="redpanda.redpanda.svc.cluster.local:9644" set write_caching_default=true
#             restartPolicy: Never
#         backoffLimit: 4

# - name: Wait for write caching job to complete
#   when: exp_params.redpanda_write_caching
#   ansible.builtin.k8s_info:
#     api_version: batch/v1
#     kind: Job
#     name: enable-write-caching
#     namespace: redpanda
#   register: job_status
#   until: >
#     'status' in job_status.resources[0] and
#     'succeeded' in job_status.resources[0].status and
#     job_status.resources[0].status.succeeded == 1
#   retries: 24
#   delay: 5

# - name: Delete write caching job
#   when: exp_params.redpanda_write_caching
#   ansible.builtin.k8s:
#     state: absent
#     definition:
#       apiVersion: batch/v1
#       kind: Job
#       metadata:
#         name: enable-write-caching
#         namespace: redpanda

- name: Deploy Kminion
  delegate_to: localhost
  kubernetes.core.helm:
    name: kminion
    create_namespace: true
    chart_ref: "{{ q('pipe', 'git rev-parse --show-toplevel')[0] }}/charts/kminion/charts/kminion"
    # chart_version: 0.8.2
    wait: true
    release_namespace: redpanda
    values: "{{ lookup('ansible.builtin.template', 'kminion-values.yaml.j2') | from_yaml }}"

- name: Deploy Service Monitor for Redpanda
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'redpanda-svcmonitor.yaml.j2') | from_yaml }}"
